### PR TITLE
MAINT: Add redo button.

### LINKED ISSUE #20: Add redo tool to DashCanvas
This is very useful when we erase the image.

### PR DESCRIPTION
**Pull request by jvkersch**
closes #20

This adds a redo button to the tools that are listed below the canvas. I've also made an attempt at putting together an integration test with Dash to check the behavior of the undo/redo buttons.

Along the way, I deleted `test_usage.py`, since it used the now-deprecated pytest-dash plugin, which conflicts with the standard dash[testing] package. I assumed its functionality would be a subset of the functionality in my integration test, but please let me know if it needs to be restored.

### CODE REVIEW

**Comment by emmanuelle** [comment]
Awesome @jvkersch thanks a lot! I have been travelling for a month so I just saw your PR, will be getting back to you soon.

**Comment by emmanuelle** [comment]
Looks good to me, thanks! Could you please just replace ``dash`` by ``dash[testing]`` in ``requirements.txt?`` Then I'll merge.

**Comment by jvkersch** [comment]
> Could you please just replace `dash` by `dash[testing]`

Done!

**Comment by emmanuelle** [comment]
Thanks a lot, merging! Now let's have CircleCI be happy again ;-)

**Pull request merged**
